### ISSUE TITLE
readme not up to date? troubles with command

### ISSUE THREAD

**Issue by awesome-crab** [csi-greifflab/Absolut#9] opened 2022-09-01 12:20 UTC
Hello everyone,

amazing paper and software!!!!!

I tried to install Absolut in a docker container and at least the nolib version seems to be working.
I am trying to run the commands in the readme section Usage.

Unfortunately I am having troubles with following command:
`./AbsolutNoLib info_filenames 1FBI_X`

`wget http://philippe-robert.com/Absolut/StructuresSULSU040643e2c0a6d6343bbe8a27b079ef91-10-11efc862c2cdef086ba79606103a3dfc62Structures.txt
`
for the first part I get the message:
`Sorry, command info_filenames could not be found/understood. Run without argument for help`

and for the wget command I get:
`Resolving philippe-robert.com (philippe-robert.com)... 217.160.0.18
Connecting to philippe-robert.com (philippe-robert.com)|217.160.0.18|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-01 12:11:30 ERROR 404: Not Found.`

from the commands list I get when running `./AbsolutNoLib` I see that the command `info_filenames` should actually be existing.

Is something wrong with my installation? Can anyone give me a hint what might be the issue?
Thanks in advance and have a nice day!!

**Comment by petouzeman** [comment] 2022-09-01 12:49
Dear Awesome-crab,
Sorry, the philippe-robert.com webpage is down and the new location is on the nird research data archive:

https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/Structures/
(example: https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/Structures/0bdfb10d531f6c4c557b2d0dd3f2b8c4-10-11-db0516f09d29bca565e5d7d698eee5a4Structures.txt.zip)

I will update the code in the coming days, sorry for this!

**Comment by petouzeman** [comment] 2022-09-01 13:10
So, I think you ave an old version of Absolut!, I tried to redownload from here and I get the following output:

```
 ... loading antigen 1FBI_X from the library
Pre-calculated structures are in SULSU040643e2c0a6d6343bbe8a27b079ef91-10-11-efc862c2cdef086ba79606103a3dfc62Structures.txt
use:
curl -O -J https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/Structures/SULSU040643e2c0a6d6343bbe8a27b079ef91-10-11-efc862c2cdef086ba79606103a3dfc62Structures.txt.zip
 and unzip it
```

We actually have pushed a newer version of Absolut from  ~April 8 2022, which should solve this and includes new features. Tell me if it works!

Best

**Comment by petouzeman** [comment] 2022-09-01 13:18
Also, no need to worry about the webpage being down, Absolut! does not communicate directly with the database or structures files online, it only uses wget to download PDB files for discretization.

If you uploaded a newer version on an existing one, maybe the compilation didn't work and you are using the executable from the previous version, I would suggest to delete the AbsolutNoLib first and recompile, this might solve the problem!

Have a nice day!

**Comment by awesome-crab** [comment] 2022-09-01 14:14
Thanks a lot for your advice!! 
I updated my Dockerfile to clone the repository and I should now have the latest code.
I directly installed the full version.

Now when I run the command `./Absolut info_filenames 1FBI_X` I get the same output as you:
`   ... loading antigen 1FBI_X from the library
Pre-calculated structures are in SULSU040643e2c0a6d6343bbe8a27b079ef91-10-11-efc862c2cdef086ba79606103a3dfc62Structures.txt
use:
curl -O -J https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/Structures/SULSU040643e2c0a6d6343bbe8a27b079ef91-10-11-efc862c2cdef086ba79606103a3dfc62Structures.txt.zip
 and unzip it`

Thanks very much for your support!!

When I tried to run the command: `./Absolut discretize 1CZ8 VW 5.25 FuC`
I got the message:
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
```

Unfortunately I am not sure if that is because I run absolut in a docker container and I cannot open any GUI, or if that is a small bug in Qt.... I just thought I am going to report this.
In the mean time an expert in my team will have a look at the paper to understand how we can create a library of annotated sequences which bind (or not) a specific antigen. Thats still kind of a miracle to me 🥲

**Comment by petouzeman** [comment] 2022-09-01 14:25
Ok, the first part is already a good news!

So, I didn't try it with a docker, so it's hard to tell if the problem comes from Qt, but of course it's sad you can not have the GUI, 

If you like you could have a try by command line if it works, these commands should work both for ./Absolut or ./AbsolutNoLib, I will try it now too
```

https://github.com/csi-greifflab/Absolut/issues/1 Selecting the chain and removing insertions
./Absolut discretize_delete_insertions 1ADQ A
output: 1ADQdeIns.pdb

https://github.com/csi-greifflab/Absolut/issues/2 Using latfit to generate a discretized PDB
./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb
output: 1ADQ_AdiscretizedFuC5.25.pdb

or with non-default parameters:
./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb 6 CoM false 40
output: 1ADQ_AdiscretizedCoM6.pdb

https://github.com/csi-greifflab/Absolut/issues/3 and last step, from the latfit output to the inLattice text file
./Absolut discretize_discrete_pdb_to_lattice 1ADQ A 1ADQ_AdiscretizedFuC5.25.pdb
output: 1ADQ_Ainlattice.txt
```

Regarding the docker, there was a previous issue where someone started a docker, it might help: https://github.com/antonkulaga/airr-seq/tree/main/containers/absolut but I didn't try it myself

**Comment by petouzeman** [comment] 2022-09-01 14:38
but it seems that people have problems with docker and Qt in general (doesn't seem super obvious), so it might not be on your side!

**Comment by awesome-crab** [comment] 2022-09-01 15:41
I tried out the commands but unfortunately I got some Error messages:
 
```
root@82eec08179b7:/Absolut/src/bin# ./Absolut discretize_delete_insertions 1ADQ A
File 1ADQ.pdb not found in the current folder
The PDB with selected chains and removed insertions was stored in (empty if failed):

root@82eec08179b7:/Absolut/src/bin# ./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb
Executing >> latFit.exe -pdbFile=1ADQdeIns.pdb -pdbAtom=FuC -pdbChain=A -pdbChainGaps -lat=CUB -outMode=PDB -outFile=1ADQ_AdiscretizedFuC5.25.pdb -opt=D -outOrigData -pdbAtomAlt=A -nKeep=20 -s -bondLength=5.25Latfit received 14 arguments
latFit.exe
-pdbFile=1ADQdeIns.pdb
-pdbAtom=FuC
-pdbChain=A
-pdbChainGaps
-lat=CUB
-outMode=PDB
-outFile=1ADQ_AdiscretizedFuC5.25.pdb
-opt=D
-outOrigData
-pdbAtomAlt=A
-nKeep=20
-s
-bondLength=5.25

   ERROR : can not open pdb file '1ADQdeIns.pdb' !

ERR: Discretization failed with latfit.
The discretized PDB file from latfit was stored in (empty if failed):

root@82eec08179b7:/Absolut/src/bin# ./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb 6 CoM false 40
Executing >> latFit.exe -pdbFile=1ADQdeIns.pdb -pdbAtom=CoM -pdbChain=A -lat=CUB -outMode=PDB -outFile=1ADQ_AdiscretizedCoM6.pdb -opt=D -outOrigData -pdbAtomAlt=A -nKeep=40 -s -bondLength=6Latfit received 13 arguments
latFit.exe
-pdbFile=1ADQdeIns.pdb
-pdbAtom=CoM
-pdbChain=A
-lat=CUB
-outMode=PDB
-outFile=1ADQ_AdiscretizedCoM6.pdb
-opt=D
-outOrigData
-pdbAtomAlt=A
-nKeep=40
-s
-bondLength=6

   ERROR : can not open pdb file '1ADQdeIns.pdb' !

ERR: Discretization failed with latfit.
The discretized PDB file from latfit was stored in (empty if failed):

root@82eec08179b7:/Absolut/src/bin# ./Absolut discretize_discrete_pdb_to_lattice 1ADQ A 1ADQ_AdiscretizedFuC5.25.pdb
ERR: latFitToLattice::parseLatFitPDB, file not found:
1ADQ_AdiscretizedFuC5.25.pdb
ERR: Could not transform discretized PDB structure into the lattice (from file: 1ADQ_AdiscretizedFuC5.25.pdb)
The lattice version of the discretized PDB was saved in:
```

Maybe my installation does not have access to pdb? Previously you mentioned, that Absolut uses wget to download pdb files. I made sure that wget is installed:
```
root@82eec08179b7:/Absolut/src/bin# apt install wget
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by petouzeman** [comment] 2022-09-01 18:29
Silly me, you are right, without the GUI, you would need to download the PDB by yourself, 

`curl "http://files.rcsb.org/download/1ADQ.pdb" > 1ADQ.pdb`

I am trying to reproduce the steps right now, let's see if it works!

**Comment by petouzeman** [comment] 2022-09-01 18:53
So, actually, the steps for discretization will only work with ./Absolut (and not ./AbsolutNoLib), I was wrong about this. 

In theory the following steps might work, or might not, depending if ./Absolut accepts to run (without opening a GUI) despite the Qt problems 

```
curl "http://files.rcsb.org/download/1ADQ.pdb" > 1ADQ.pdb
./Absolut discretize_delete_insertions 1ADQ A
./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb
./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb 6 CoM false 40
./Absolut discretize_discrete_pdb_to_lattice 1ADQ A 1ADQ_AdiscretizedFuC5.25.pdb

```

Tell me if it works!

If it still blocks because of Qt then I think this is more of a docker problem and I have very poor experience with it. To avoid destroying your config, one possibility would be to use a linux virtual box (I usually do it for testing), but it's a bit efforts...

Also, independently, I can recommend the mp4 video in the main folder, it might help, (but you probably have already seen it).

**Comment by awesome-crab** [comment] 2022-09-02 11:48
I tried the commands and first I encountered an Error:

`sh: 1: python: not found`

I solved this issue by renaming the python3 to python:

```
root@3edd4663fa25:/Absolut/src/bin# which python
root@3edd4663fa25:/Absolut/src/bin# which python3
/usr/bin/python3
root@3edd4663fa25:/# cd usr/bin/
root@3edd4663fa25:/usr/bin# mv python3 python
```

After that the commands worked:

```
root@3edd4663fa25:/Absolut/src/bin# ./Absolut discretize_delete_insertions 1ADQ A
Executing >> python "../pdb-tools/pdbtools/pdb_delinsertion.py" 1ADQ.pdb > 1ADQdeIns.pdb
The PDB with selected chains and removed insertions was stored in (empty if failed):1ADQdeIns.pdb

root@3edd4663fa25:/Absolut/src/bin# ./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb
Executing >> latFit.exe -pdbFile=1ADQdeIns.pdb -pdbAtom=FuC -pdbChain=A -pdbChainGaps -lat=CUB -outMode=PDB -outFile=1ADQ_AdiscretizedFuC5.25.pdb -opt=D -outOrigData -pdbAtomAlt=A -nKeep=20 -s -bondLength=5.25Latfit received 14 arguments
latFit.exe
-pdbFile=1ADQdeIns.pdb
-pdbAtom=FuC
-pdbChain=A
-pdbChainGaps
-lat=CUB
-outMode=PDB
-outFile=1ADQ_AdiscretizedFuC5.25.pdb
-opt=D
-outOrigData
-pdbAtomAlt=A
-nKeep=20
-s
-bondLength=5.25

The discretized PDB file from latfit was stored in (empty if failed):1ADQ_AdiscretizedFuC5.25.pdb

root@3edd4663fa25:/Absolut/src/bin#
./Absolut discretize_latfit_to_discrete_pdb 1ADQ A 1ADQdeIns.pdb 6 CoM false 40
Executing >> latFit.exe -pdbFile=1ADQdeIns.pdb -pdbAtom=CoM -pdbChain=A -lat=CUB -outMode=PDB -outFile=1ADQ_AdiscretizedCoM6.pdb -opt=D -outOrigData -pdbAtomAlt=A -nKeep=40 -s -bondLength=6Latfit received 13 arguments
latFit.exe
-pdbFile=1ADQdeIns.pdb
-pdbAtom=CoM
-pdbChain=A
-lat=CUB
-outMode=PDB
-outFile=1ADQ_AdiscretizedCoM6.pdb
-opt=D
-outOrigData
-pdbAtomAlt=A
-nKeep=40
-s
-bondLength=6

The discretized PDB file from latfit was stored in (empty if failed):1ADQ_AdiscretizedCoM6.pdb

./Absolut discretize_discrete_pdb_to_lattice 1ADQ A 1ADQ_AdiscretizedFuC5.25.pdb
```

I guess I will need to check if the ruslt files are correct but I think Absolut works fine in docker.

Thanks a lot for your support!!

**Comment by petouzeman** [comment] 2022-09-04 07:15
That is super nice to hear! 
Have a nice day!

**Comment by petouzeman** [comment] 2022-09-04 07:16
I will close the issue, Best,

**Closed by petouzeman** 2022-09-04 07:15 UTC
