### ISSUE TITLE
Crash when patching Glycans on Linux

### ISSUE THREAD

**Issue by YannickVogt** [csi-greifflab/Absolut#17] opened 2023-03-22 10:15 UTC
Hello,

I'm trying to discretize chain C of 1N8Z and create the corresponding 1N8Z_Cinlattice.txt to integrate it into AntigenLib.cpp. Discretizing the structure works and 1N8Z_CdiscretizedFuC5.25.pdb is successfully created. However, when trying to create the final 1N8Z_Cinlattice.txt using either the GUI or command line I receive the following error when patching Glycans.

```
Looking for glycans in 1N8Z.pdb
AAC165ASN interacts with C766	found 42 positions	Glycan C766 Has center at -28.7499,92.1122,159.481	AAposition is -29.6209	87.9262	156.985
AAC237ASN interacts with C738	found 42 positions	Glycan C738 Has center at -19.7955,72.6179,121.09	AAposition is -16.121	69.2677	122.582
Found 2Glycans
Found 2 Glycans in the original PDB. Will patch them now 

Glycan1/2: real -28.7499,92.1122,159.481 => rescaled at 33.2312 34.4269 40.3643
ERR: wrong length of vectors in operator ^
Segmentation fault (core dumped)
```
The same issue arises with other PDBs containing Glycans.
Is there a way I can resolve this issue?

Best regards
Yannick

**Comment by petouzeman** [comment] 2023-03-23 06:07
Dear Yannick, 
Interesting, will look at it, give me a few days and i will come back!
Best,
Philippe

**Comment by YannickVogt** [comment] 2023-04-11 10:35
Dear @petouzeman ,
are there any updates regarding this issue?

Best,
Yannick

**Comment by petouzeman** [comment] 2023-05-01 06:47
Hi, I am super sorry for delay, I am changing job and got trapped into deadlines, 

So, I had a look and I can not reproduce the problem, but your problem is a C++ problem. I would suggest to try with the latest version of Absolut, not sure which one you were using. it could also be that one file generated by the process got corrupted or so, you could have a look by making a clean compiled version and removing previously generated files, that could help.

For info, this is the output I get:

File 1N8Z.pdb was found in the folder, no need to download!
Executing >> curl "https://www.rcsb.org/fasta/entry/1N8Z/download" > 1N8Z.fa
Executing >> python "../pdb-tools/pdbtools/pdb_delinsertion.py" 1N8Z.pdb > 1N8ZdeIns.pdb
Looking for glycans in 1N8Z.pdb
AAC165ASN interacts with C766	found 42 positions	Glycan C766 Has center at -28.7499,92.1122,159.481	AAposition is -29.6209	87.9262	156.985
AAC237ASN interacts with C738	found 42 positions	Glycan C738 Has center at -19.7955,72.6179,121.09	AAposition is -16.121	69.2677	122.582
Found 2Glycans
Executing >> latFit.exe -pdbFile=1N8ZdeIns.pdb -pdbAtom=FuC -pdbChain=C -pdbChainGaps -lat=CUB -outMode=PDB -outFile=1N8Z_CdiscretizedFuC5.25.pdb -opt=D -outOrigData -pdbAtomAlt=A -nKeep=25 -s -bondLength=5.25Latfit received 14 arguments 
latFit.exe
-pdbFile=1N8ZdeIns.pdb
-pdbAtom=FuC
-pdbChain=C
-pdbChainGaps
-lat=CUB
-outMode=PDB
-outFile=1N8Z_CdiscretizedFuC5.25.pdb
-opt=D
-outOrigData
-pdbAtomAlt=A
-nKeep=25
-s
-bondLength=5.25

Looking for glycans in 1N8Z.pdb
AAC165ASN interacts with C766	found 42 positions	Glycan C766 Has center at -28.7499,92.1122,159.481	AAposition is -29.6209	87.9262	156.985
AAC237ASN interacts with C738	found 42 positions	Glycan C738 Has center at -19.7955,72.6179,121.09	AAposition is -16.121	69.2677	122.582
Found 2Glycans
Found 2 Glycans in the original PDB. Will patch them now 

Glycan1/2: real -28.7499,92.1122,159.481 => rescaled at 31.5463 30.0732 40.5586
Found AA at ID 155
   Found matching AA, original pos -29.621	87.926	156.985, afterr latfit -28.708	89.521	156.704 and rescaled 32.0005,30.0009,40.0002 => 32	30	40
   ID possible neighbors are: 
  -> 165793, 33	30	40
  -> 165791, 31	30	40
  -> 165856, 32	31	40
  -> 165728, 32	29	40
  -> 169888, 32	30	41
  -> 161696, 32	30	39
   => ID remaining free positions for this glycan are: 165856 169888 

Glycan2/2: real -19.7955,72.6179,121.09 => rescaled at 34.57 30.3436 32.7515
Found AA at ID 227
   Found matching AA, original pos -16.121	69.268	122.582, afterr latfit -11.909	69.726	124.536 and rescaled 34.9999,32.0002,32.9999 => 35	32	33
   ID possible neighbors are: 
  -> 137252, 36	32	33
  -> 137250, 34	32	33
  -> 137315, 35	33	33
  -> 137187, 35	31	33
  -> 141347, 35	32	34
  -> 133155, 35	32	32
WRN: The AA that is bound by this glycan is NOT A SURFACE AA => Taking the neighbors of the glycan instead!!
  -> 133027, 35	30	32
  -> 133025, 33	30	32
  -> 133090, 34	31	32
  -> 132962, 34	29	32
  -> 137122, 34	30	33
  -> 128930, 34	30	31
  -> 133026, 34	30	32
   => ID remaining free positions for this glycan are: 128930 132962 133025 133026 133027 137122 
List of priorities for each glycan
Glycan 0		169888->32	30	41,d=0.798221	165856->32	31	40,d=1.08323
Glycan 1		137122->34	30	33,d=0.842886	133027->35	30	32,d=0.965154	133026->34	30	32,d=1.00194	132962->34	29	32,d=1.28127	133025->33	30	32,d=1.332	128930->34	30	31,d=1.36884
Glycan 0 attributed to position 169888
Glycan 1 attributed to position 137122
Found 2 positions for 2 Glycans 
Looking for glycans in 1N8Z.pdb
AAC165ASN interacts with C766	found 42 positions	Glycan C766 Has center at -28.7499,92.1122,159.481	AAposition is -29.6209	87.9262	156.985
AAC237ASN interacts with C738	found 42 positions	Glycan C738 Has center at -19.7955,72.6179,121.09	AAposition is -16.121	69.2677	122.582
Found 2Glycans
Found 2 Glycans in the original PDB. Will patch them now 

Glycan1/2: real -28.7499,92.1122,159.481 => rescaled at 31.5463 30.0732 40.5586
Found AA at ID 155
   Found matching AA, original pos -29.621	87.926	156.985, afterr latfit -28.708	89.521	156.704 and rescaled 32.0005,30.0009,40.0002 => 32	30	40
   ID possible neighbors are: 
  -> 165793, 33	30	40
  -> 165791, 31	30	40
  -> 165856, 32	31	40
  -> 165728, 32	29	40
  -> 169888, 32	30	41
  -> 161696, 32	30	39
   => ID remaining free positions for this glycan are: 165856 169888 

Glycan2/2: real -19.7955,72.6179,121.09 => rescaled at 34.57 30.3436 32.7515
Found AA at ID 227
   Found matching AA, original pos -16.121	69.268	122.582, afterr latfit -11.909	69.726	124.536 and rescaled 34.9999,32.0002,32.9999 => 35	32	33
   ID possible neighbors are: 
  -> 137252, 36	32	33
  -> 137250, 34	32	33
  -> 137315, 35	33	33
  -> 137187, 35	31	33
  -> 141347, 35	32	34
  -> 133155, 35	32	32
WRN: The AA that is bound by this glycan is NOT A SURFACE AA => Taking the neighbors of the glycan instead!!
  -> 133027, 35	30	32
  -> 133025, 33	30	32
  -> 133090, 34	31	32
  -> 132962, 34	29	32
  -> 137122, 34	30	33
  -> 128930, 34	30	31
  -> 133026, 34	30	32
   => ID remaining free positions for this glycan are: 128930 132962 133025 133026 133027 137122 
List of priorities for each glycan
Glycan 0		169888->32	30	41,d=0.798221	165856->32	31	40,d=1.08323
Glycan 1		137122->34	30	33,d=0.842886	133027->35	30	32,d=0.965154	133026->34	30	32,d=1.00194	132962->34	29	32,d=1.28127	133025->33	30	32,d=1.332	128930->34	30	31,d=1.36884
Glycan 0 attributed to position 169888
Glycan 1 attributed to position 137122
Found 2 positions for 2 Glycans

**Comment by petouzeman** [comment] 2023-05-01 06:53
Also, I did discretize 1NZ8 in the past and I got some problems because it has huge pockets inside, and any antibodies/binding structures you would test will be inside the antigen, I would suggest you to look at 1S78 which I believe is also HER2 and doesn't have this problem, and you may have it commented in the antigenLib.cpp or so, but maybe better that you try to discretize it first.
I am in China now for 2 weeks so a bit bad internet, but I will try to be reponsive, tell me what happens!
Best,

**Comment by YannickVogt** [comment] 2023-05-08 07:49
Dear Philippe,

thank you for your response and the hints wrt. 1N8Z in particular.
It is indeed a C++ problem. Reinstalling Absolut! using the gcc compiler v10 instead of v11 allows me to discretize the antigen via the command line, using the following steps:
```
./Absolut discretize_delete_insertions 1N8Z C 
./Absolut discretize_latfit_to_discrete_pdb  1N8Z  C  1N8ZdeIns.pdb
./Absolut discretize_discrete_pdb_to_lattice 1N8Z C 1N8Z_CdiscretizedFuC5.25.pdb 
```
The resulting discretized pdb looks reasonable from my layman's perspective.

Interestingly, if I try to reproduce the results using the GUI it crashes during the 'Merge chains into file'-step resulting in the error below which is equivalent to the one I received last time. I have no insights into where the mismatch between the command line and GUI stems from.
```
Executing >>  curl "http://files.rcsb.org/download/1N8Z.pdb" > 1N8Z.pdb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  686k    0  686k    0     0   808k      0 --:--:-- --:--:-- --:--:--  808k
Executing >> curl "https://www.rcsb.org/fasta/entry/1N8Z/download" > 1N8Z.fa
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1272  100  1272    0     0   3473      0 --:--:-- --:--:-- --:--:--  3475
Executing >> python "../pdb-tools/pdbtools/pdb_delinsertion.py" 1N8Z.pdb > 1N8ZdeIns.pdb
Looking for glycans in 1N8Z.pdb
AAC165ASN interacts with C766	found 42 positions	Glycan C766 Has center at -28.7499,92.1122,159.481	AAposition is -29.6209	87.9262	156.985
AAC237ASN interacts with C738	found 42 positions	Glycan C738 Has center at -19.7955,72.6179,121.09	AAposition is -16.121	69.2677	122.582
Found 2Glycans
Executing >> latFit.exe -pdbFile=1N8ZdeIns.pdb -pdbAtom=FuC -pdbChain=C -pdbChainGaps -lat=CUB -outMode=PDB -outFile=1N8Z_CdiscretizedFuC5.25.pdb -opt=D -outOrigData -pdbAtomAlt=A -nKeep=25 -s -bondLength=5.25Latfit received 14 arguments 
latFit.exe
-pdbFile=1N8ZdeIns.pdb
-pdbAtom=FuC
-pdbChain=C
-pdbChainGaps
-lat=CUB
-outMode=PDB
-outFile=1N8Z_CdiscretizedFuC5.25.pdb
-opt=D
-outOrigData
-pdbAtomAlt=A
-nKeep=25
-s
-bondLength=5.25

Looking for glycans in 1N8Z.pdb
AAC165ASN interacts with C766	found 42 positions	Glycan C766 Has center at -28.7499,92.1122,159.481	AAposition is -29.6209	87.9262	156.985
AAC237ASN interacts with C738	found 42 positions	Glycan C738 Has center at -19.7955,72.6179,121.09	AAposition is -16.121	69.2677	122.582
Found 2Glycans
Found 2 Glycans in the original PDB. Will patch them now 

Glycan1/2: real -28.7499,92.1122,159.481 => rescaled at 33.2312 34.4269 40.3643
ERR: wrong length of vectors in operator ^
```
Perhaps this is of interest to you. I am using the current Absolut version, Ubuntu 22.04, and c++ v11.3.0.

Best regards,
Yannick

**Closed** 2023-06-28 07:46 UTC
